DROP TABLE IF EXITS users;
DROP TABLE IF EXISTS logins;

CREATE TABLE users (
	user_id INT PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL,
	joined_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE tasks (
	user_id INT PRIMARY KEY AUTOINNCREMENT,
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	FOREIGN KEY (task) REFERENCES users (id)
);

